version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: rabbitTest:${RABBITTEST_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
    environment:
      RABBITTEST_HOST: 0.0.0.0
      RABBITTEST_DB_HOST: rabbitTest-db
      RABBITTEST_DB_PORT: 3306
      RABBITTEST_DB_USER: rabbitTest
      RABBITTEST_DB_PASS: rabbitTest
      RABBITTEST_DB_BASE: rabbitTest
      RABBITTEST_RABBIT_HOST: rabbitTest-rmq

  db:
    image: bitnami/mysql:8.0.30
    hostname: rabbitTest-db
    restart: always
    environment:
      MYSQL_ROOT_USER: "rabbitTest"
      MYSQL_ROOT_PASSWORD: "rabbitTest"
      MYSQL_DATABASE: "rabbitTest"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
      - rabbitTest-db-data:/bitnami/mysql/data

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "rabbitTest-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50



volumes:
  rabbitTest-db-data:
    name: rabbitTest-db-data
